"""Remove unused models

Revision ID: 0a12f9571cb2
Revises: 8394ded96cd2
Create Date: 2026-07-19 21:02:29.892639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0a12f9571cb2'
down_revision: Union[str, None] = '8394ded96cd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_media_file_name', table_name='media')
    op.drop_index('ix_media_mime_type', table_name='media')
    op.drop_table('media')
    op.drop_index('ix_prayers_status', table_name='prayers')
    op.drop_index('ix_prayers_title', table_name='prayers')
    op.drop_table('prayers')
    op.drop_index('ix_posters_status', table_name='posters')
    op.drop_index('ix_posters_template_id', table_name='posters')
    op.drop_index('ix_posters_title', table_name='posters')
    op.drop_table('posters')
    op.drop_index('ix_poster_templates_name', table_name='poster_templates')
    op.drop_table('poster_templates')
    op.drop_index('ix_announcements_published', table_name='announcements')
    op.drop_index('ix_announcements_title', table_name='announcements')
    op.drop_table('announcements')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posters',
    sa.Column('template_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['poster_templates.id'], name='fk_posters_template_id_poster_templates', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='pk_posters')
    )
    op.create_index('ix_posters_title', 'posters', ['title'], unique=False)
    op.create_index('ix_posters_template_id', 'posters', ['template_id'], unique=False)
    op.create_index('ix_posters_status', 'posters', ['status'], unique=False)
    op.create_table('announcements',
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('body', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('published', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_announcements')
    )
    op.create_index('ix_announcements_title', 'announcements', ['title'], unique=False)
    op.create_index('ix_announcements_published', 'announcements', ['published'], unique=False)
    op.create_table('poster_templates',
    sa.Column('name', sa.VARCHAR(length=160), autoincrement=False, nullable=False),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_poster_templates')
    )
    op.create_index('ix_poster_templates_name', 'poster_templates', ['name'], unique=True)
    op.create_table('prayers',
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_prayers')
    )
    op.create_index('ix_prayers_title', 'prayers', ['title'], unique=False)
    op.create_index('ix_prayers_status', 'prayers', ['status'], unique=False)
    op.create_table('media',
    sa.Column('file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('storage_key', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('mime_type', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('size_bytes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_media'),
    sa.UniqueConstraint('storage_key', name='uq_media_storage_key', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index('ix_media_mime_type', 'media', ['mime_type'], unique=False)
    op.create_index('ix_media_file_name', 'media', ['file_name'], unique=False)
    # ### end Alembic commands ###
