"""Add Sermon Intelligence Engine models

Revision ID: 9ac0d49238b1
Revises: b688031139ce
Create Date: 2026-07-19 20:16:51.703357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9ac0d49238b1'
down_revision: Union[str, None] = 'b688031139ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sermon_tags',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sermon_tags'))
    )
    op.create_index(op.f('ix_sermon_tags_name'), 'sermon_tags', ['name'], unique=True)
    op.create_table('sermon_templates',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('structure', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sermon_templates'))
    )
    op.create_index(op.f('ix_sermon_templates_name'), 'sermon_templates', ['name'], unique=True)
    op.create_table('sermon_history',
    sa.Column('sermon_id', sa.UUID(), nullable=False),
    sa.Column('content_snapshot', sa.Text(), nullable=False),
    sa.Column('version_note', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sermon_id'], ['sermons.id'], name=op.f('fk_sermon_history_sermon_id_sermons'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sermon_history'))
    )
    op.create_index(op.f('ix_sermon_history_sermon_id'), 'sermon_history', ['sermon_id'], unique=False)
    op.create_table('sermon_sections',
    sa.Column('sermon_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sermon_id'], ['sermons.id'], name=op.f('fk_sermon_sections_sermon_id_sermons'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sermon_sections'))
    )
    op.create_index(op.f('ix_sermon_sections_sermon_id'), 'sermon_sections', ['sermon_id'], unique=False)
    op.create_table('sermon_tags_link',
    sa.Column('sermon_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['sermon_id'], ['sermons.id'], name=op.f('fk_sermon_tags_link_sermon_id_sermons'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['sermon_tags.id'], name=op.f('fk_sermon_tags_link_tag_id_sermon_tags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sermon_id', 'tag_id', name=op.f('pk_sermon_tags_link'))
    )
    op.create_table('sermon_references',
    sa.Column('sermon_id', sa.UUID(), nullable=False),
    sa.Column('verse_id', sa.UUID(), nullable=False),
    sa.Column('reference_string', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sermon_id'], ['sermons.id'], name=op.f('fk_sermon_references_sermon_id_sermons'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verse_id'], ['bible_verses.id'], name=op.f('fk_sermon_references_verse_id_bible_verses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sermon_references'))
    )
    op.create_index(op.f('ix_sermon_references_sermon_id'), 'sermon_references', ['sermon_id'], unique=False)
    op.create_index(op.f('ix_sermon_references_verse_id'), 'sermon_references', ['verse_id'], unique=False)
    op.add_column('sermons', sa.Column('theme', sa.String(length=255), nullable=True))
    op.add_column('sermons', sa.Column('main_verse', sa.String(length=255), nullable=True))
    op.add_column('sermons', sa.Column('bible_version', sa.String(length=50), nullable=False))
    op.add_column('sermons', sa.Column('audience', sa.String(length=255), nullable=True))
    op.add_column('sermons', sa.Column('occasion', sa.String(length=255), nullable=True))
    op.add_column('sermons', sa.Column('estimated_duration', sa.Integer(), nullable=True))
    op.add_column('sermons', sa.Column('date_preached', sa.String(length=50), nullable=True))
    op.add_column('sermons', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sermons', 'notes')
    op.drop_column('sermons', 'date_preached')
    op.drop_column('sermons', 'estimated_duration')
    op.drop_column('sermons', 'occasion')
    op.drop_column('sermons', 'audience')
    op.drop_column('sermons', 'bible_version')
    op.drop_column('sermons', 'main_verse')
    op.drop_column('sermons', 'theme')
    op.drop_index(op.f('ix_sermon_references_verse_id'), table_name='sermon_references')
    op.drop_index(op.f('ix_sermon_references_sermon_id'), table_name='sermon_references')
    op.drop_table('sermon_references')
    op.drop_table('sermon_tags_link')
    op.drop_index(op.f('ix_sermon_sections_sermon_id'), table_name='sermon_sections')
    op.drop_table('sermon_sections')
    op.drop_index(op.f('ix_sermon_history_sermon_id'), table_name='sermon_history')
    op.drop_table('sermon_history')
    op.drop_index(op.f('ix_sermon_templates_name'), table_name='sermon_templates')
    op.drop_table('sermon_templates')
    op.drop_index(op.f('ix_sermon_tags_name'), table_name='sermon_tags')
    op.drop_table('sermon_tags')
    # ### end Alembic commands ###
