"""add_missing_tables

Revision ID: af2d4826e0a2
Revises: 0a12f9571cb2
Create Date: 2026-07-21 17:33:23.894520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'af2d4826e0a2'
down_revision: Union[str, None] = '0a12f9571cb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_folders',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_folders'))
    )
    op.create_table('asset_tags',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_tags')),
    sa.UniqueConstraint('name', name=op.f('uq_asset_tags_name'))
    )
    op.create_table('brand_profiles',
    sa.Column('church_id', sa.UUID(), nullable=False),
    sa.Column('logo_url', sa.String(length=512), nullable=True),
    sa.Column('primary_color', sa.String(length=50), nullable=False),
    sa.Column('secondary_color', sa.String(length=50), nullable=False),
    sa.Column('accent_color', sa.String(length=50), nullable=False),
    sa.Column('heading_font', sa.String(length=100), nullable=False),
    sa.Column('body_font', sa.String(length=100), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('social_handles', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('church_motto', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['church_id'], ['churches.id'], name=op.f('fk_brand_profiles_church_id_churches'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brand_profiles'))
    )
    op.create_index(op.f('ix_brand_profiles_church_id'), 'brand_profiles', ['church_id'], unique=True)
    op.create_table('communication_projects',
    sa.Column('sermon_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('campaign_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sermon_id'], ['sermons.id'], name=op.f('fk_communication_projects_sermon_id_sermons'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_communication_projects'))
    )
    op.create_index(op.f('ix_communication_projects_campaign_type'), 'communication_projects', ['campaign_type'], unique=False)
    op.create_index(op.f('ix_communication_projects_sermon_id'), 'communication_projects', ['sermon_id'], unique=False)
    op.create_index(op.f('ix_communication_projects_title'), 'communication_projects', ['title'], unique=False)
    op.create_table('creative_projects',
    sa.Column('sermon_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('media_type', sa.String(length=50), nullable=False),
    sa.Column('target_dimensions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('editor_state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('ai_prompt', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sermon_id'], ['sermons.id'], name=op.f('fk_creative_projects_sermon_id_sermons'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_creative_projects'))
    )
    op.create_index(op.f('ix_creative_projects_media_type'), 'creative_projects', ['media_type'], unique=False)
    op.create_index(op.f('ix_creative_projects_sermon_id'), 'creative_projects', ['sermon_id'], unique=False)
    op.create_index(op.f('ix_creative_projects_title'), 'creative_projects', ['title'], unique=False)
    op.create_table('communication_assets',
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('platform', sa.String(length=100), nullable=False),
    sa.Column('content_length', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['communication_projects.id'], name=op.f('fk_communication_assets_project_id_communication_projects'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_communication_assets'))
    )
    op.create_index(op.f('ix_communication_assets_platform'), 'communication_assets', ['platform'], unique=False)
    op.create_index(op.f('ix_communication_assets_project_id'), 'communication_assets', ['project_id'], unique=False)
    op.create_table('creative_assets',
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('folder_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('asset_type', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['asset_folders.id'], name=op.f('fk_creative_assets_folder_id_asset_folders'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['creative_projects.id'], name=op.f('fk_creative_assets_project_id_creative_projects'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_creative_assets'))
    )
    op.create_index(op.f('ix_creative_assets_asset_type'), 'creative_assets', ['asset_type'], unique=False)
    op.create_index(op.f('ix_creative_assets_project_id'), 'creative_assets', ['project_id'], unique=False)
    op.create_index(op.f('ix_creative_assets_title'), 'creative_assets', ['title'], unique=False)
    op.create_table('asset_tags_link',
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['creative_assets.id'], name=op.f('fk_asset_tags_link_asset_id_creative_assets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['asset_tags.id'], name=op.f('fk_asset_tags_link_tag_id_asset_tags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('asset_id', 'tag_id', name=op.f('pk_asset_tags_link'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asset_tags_link')
    op.drop_index(op.f('ix_creative_assets_title'), table_name='creative_assets')
    op.drop_index(op.f('ix_creative_assets_project_id'), table_name='creative_assets')
    op.drop_index(op.f('ix_creative_assets_asset_type'), table_name='creative_assets')
    op.drop_table('creative_assets')
    op.drop_index(op.f('ix_communication_assets_project_id'), table_name='communication_assets')
    op.drop_index(op.f('ix_communication_assets_platform'), table_name='communication_assets')
    op.drop_table('communication_assets')
    op.drop_index(op.f('ix_creative_projects_title'), table_name='creative_projects')
    op.drop_index(op.f('ix_creative_projects_sermon_id'), table_name='creative_projects')
    op.drop_index(op.f('ix_creative_projects_media_type'), table_name='creative_projects')
    op.drop_table('creative_projects')
    op.drop_index(op.f('ix_communication_projects_title'), table_name='communication_projects')
    op.drop_index(op.f('ix_communication_projects_sermon_id'), table_name='communication_projects')
    op.drop_index(op.f('ix_communication_projects_campaign_type'), table_name='communication_projects')
    op.drop_table('communication_projects')
    op.drop_index(op.f('ix_brand_profiles_church_id'), table_name='brand_profiles')
    op.drop_table('brand_profiles')
    op.drop_table('asset_tags')
    op.drop_table('asset_folders')
    # ### end Alembic commands ###
